namespace System.Windows.Forms.VisualStyles;

internal enum ARROWBTNSTATES
{
	ABS_UPNORMAL = 1,
	ABS_UPHOT,
	ABS_UPPRESSED,
	ABS_UPDISABLED,
	ABS_DOWNNORMAL,
	ABS_DOWNHOT,
	ABS_DOWNPRESSED,
	ABS_DOWNDISABLED,
	ABS_LEFTNORMAL,
	ABS_LEFTHOT,
	ABS_LEFTPRESSED,
	ABS_LEFTDISABLED,
	ABS_RIGHTNORMAL,
	ABS_RIGHTHOT,
	ABS_RIGHTPRESSED,
	ABS_RIGHTDISABLED,
	ABS_UPHOVER,
	ABS_DOWNHOVER,
	ABS_LEFTHOVER,
	ABS_RIGHTHOVER
}
