namespace System.Windows.Forms.VisualStyles;

internal enum CHECKBOXSTATES
{
	CBS_UNCHECKEDNORMAL = 1,
	CBS_UNCHECKEDHOT,
	CBS_UNCHECKEDPRESSED,
	CBS_UNCHECKEDDISABLED,
	CBS_CHECKEDNORMAL,
	CBS_CHECKEDHOT,
	CBS_CHECKEDPRESSED,
	CBS_CHECKEDDISABLED,
	CBS_MIXEDNORMAL,
	CBS_MIXEDHOT,
	CBS_MIXEDPRESSED,
	CBS_MIXEDDISABLED
}
