namespace System.Windows.Forms.VisualStyles;

internal enum RADIOBUTTONSTATES
{
	RBS_UNCHECKEDNORMAL = 1,
	RBS_UNCHECKEDHOT,
	RBS_UNCHECKEDPRESSED,
	RBS_UNCHECKEDDISABLED,
	RBS_CHECKEDNORMAL,
	RBS_CHECKEDHOT,
	RBS_CHECKEDPRESSED,
	RBS_CHECKEDDISABLED
}
