namespace System.Windows.Forms.VisualStyles;

internal enum SCROLLBARPARTS
{
	SBP_ARROWBTN = 1,
	SBP_THUMBBTNHORZ,
	SBP_THUMBBTNVERT,
	SBP_LOWERTRACKHORZ,
	SBP_UPPERTRACKHORZ,
	SBP_LOWERTRACKVERT,
	SBP_UPPERTRACKVERT,
	SBP_GRIPPERHORZ,
	SBP_GRIPPERVERT,
	SBP_SIZEBOX
}
