namespace System.Windows.Forms.VisualStyles;

internal enum TABPARTS
{
	TABP_TABITEM = 1,
	TABP_TABITEMLEFTEDGE,
	TABP_TABITEMRIGHTEDGE,
	TABP_TABITEMBOTHEDGE,
	TABP_TOPTABITEM,
	TABP_TOPTABITEMLEFTEDGE,
	TABP_TOPTABITEMRIGHTEDGE,
	TABP_TOPTABITEMBOTHEDGE,
	TABP_PANE,
	TABP_BODY
}
