namespace Un4seen.Bass.AddOn.Midi;

public enum BASSMIDIMarker
{
	BASS_MIDI_MARK_MARKER = 0,
	BASS_MIDI_MARK_CUE = 1,
	BASS_MIDI_MARK_LYRIC = 2,
	BASS_MIDI_MARK_TEXT = 3,
	BASS_MIDI_MARK_TIMESIG = 4,
	BASS_MIDI_MARK_KEYSIG = 5,
	BASS_MIDI_MARK_COPY = 6,
	BASS_MIDI_MARK_TRACK = 7,
	BASS_MIDI_MARK_INST = 8,
	BASS_MIDI_MARK_TRACKSTART = 9,
	BASS_MIDI_MARK_TICK = 65536
}
