namespace Un4seen.BassAsio;

public enum BASSASIOFormat
{
	BASS_ASIO_FORMAT_UNKNOWN = -1,
	BASS_ASIO_FORMAT_16BIT = 16,
	BASS_ASIO_FORMAT_24BIT = 17,
	BASS_ASIO_FORMAT_32BIT = 18,
	BASS_ASIO_FORMAT_FLOAT = 19,
	BASS_ASIO_FORMAT_DSD_LSB = 32,
	BASS_ASIO_FORMAT_DSD_MSB = 33,
	BASS_ASIO_FORMAT_DITHER = 256
}
