namespace Un4seen.Bass.AddOn.Cd;

public enum BASSCDId
{
	BASS_CDID_UPC = 1,
	BASS_CDID_CDDB = 2,
	BASS_CDID_CDDB2 = 3,
	BASS_CDID_TEXT = 4,
	BASS_CDID_CDPLAYER = 5,
	BASS_CDID_MUSICBRAINZ = 6,
	BASS_CDID_ISRC = 256,
	BASS_CDID_CDDB_QUERY = 512,
	BASS_CDID_CDDB_READ = 513,
	BASS_CDID_CDDB_READ_CACHE = 767
}
