namespace Un4seen.BassWasapi;

public enum BASSWASAPINotify
{
	BASS_WASAPI_NOTIFY_ENABLED = 0,
	BASS_WASAPI_NOTIFY_DISABLED = 1,
	BASS_WASAPI_NOTIFY_DEFOUTPUT = 2,
	BASS_WASAPI_NOTIFY_DEFINPUT = 3,
	BASS_WASAPI_NOTIFY_FAIL = 256
}
