namespace Un4seen.BassWasapi;

public enum BASSWASAPIVolume
{
	BASS_WASAPI_CURVE_DB = 0,
	BASS_WASAPI_CURVE_LINEAR = 1,
	BASS_WASAPI_CURVE_WINDOWS = 2,
	BASS_WASAPI_VOL_SESSION = 8,
	BASS_WASAPI_VOL_DEVICE = 0
}
