using System.Collections.Generic;

namespace UnityEngine.Playables;

public interface IPlayableAsset
{
	/// <summary>
	///   <para>Duration in seconds.</para>
	/// </summary>
	double duration { get; }

	/// <summary>
	///   <para>A description of the PlayableOutputs generated by this asset.</para>
	/// </summary>
	IEnumerable<PlayableBinding> outputs { get; }

	/// <summary>
	///   <para>Implement this method to have your asset inject playables into the given graph.</para>
	/// </summary>
	/// <param name="graph">The graph to inject playables into.</param>
	/// <param name="owner">The game object which initiated the build.</param>
	/// <returns>
	///   <para>The playable injected into the graph, or the root playable if multiple playables are injected.</para>
	/// </returns>
	Playable CreatePlayable(PlayableGraph graph, GameObject owner);
}
