namespace Un4seen.Bass.AddOn.DShow;

public enum BASSDSHOWDVDSetProperty
{
	BASS_DSHOW_DVD_TITLEMENU = 100,
	BASS_DSHOW_DVD_ROOT = 101,
	BASS_DSHOW_DVD_NEXTCHAPTER = 102,
	BASS_DSHOW_DVD_PREVCHAPTER = 103,
	BASS_DSHOW_DVD_TITLE = 104,
	BASS_DSHOW_DVD_TITLECHAPTER = 105,
	BASS_DSHOW_DVDCurrentTitlePosition = 146
}
