namespace Leap;

public enum LeapEvent
{
	EVENT_CONNECTION,
	EVENT_CONNECTION_LOST,
	EVENT_DEVICE,
	EVENT_DEVICE_FAILURE,
	EVENT_DEVICE_LOST,
	EVENT_POLICY_CHANGE,
	EVENT_CONFIG_RESPONSE,
	EVENT_CONFIG_CHANGE,
	EVENT_FRAME,
	EVENT_INTERNAL_FRAME,
	EVENT_IMAGE_COMPLETE,
	EVENT_IMAGE_REQUEST_FAILED,
	EVENT_DISTORTION_CHANGE,
	EVENT_LOG_EVENT,
	EVENT_INIT,
	EVENT_DROPPED_FRAME,
	EVENT_IMAGE,
	EVENT_POINT_MAPPING_CHANGE,
	EVENT_HEAD_POSE
}
