namespace Un4seen.Bass.AddOn.Sfx;

public enum BASSSFXError
{
	BASS_SFX_OK = 0,
	BASS_SFX_ERROR_MEM = 1,
	BASS_SFX_ERROR_FILEOPEN = 2,
	BASS_SFX_ERROR_HANDLE = 3,
	BASS_SFX_ERROR_ALREADY = 4,
	BASS_SFX_ERROR_FORMAT = 5,
	BASS_SFX_ERROR_INIT = 6,
	BASS_SFX_ERROR_GUID = 7,
	BASS_SFX_ERROR_UNKNOWN = -1
}
