namespace radio42.Multimedia.Midi;

public enum MIDIError
{
	MIDI_OK = 0,
	MIDI_ERROR_ERROR = 1,
	MIDI_ERROR_BADDEVICEID = 2,
	MIDI_ERROR_NOTENABLED = 3,
	MIDI_ERROR_ALLOCATED = 4,
	MIDI_ERROR_INVALHANDLE = 5,
	MIDI_ERROR_NODRIVER = 6,
	MIDI_ERROR_NOMEM = 7,
	MIDI_ERROR_NOTSUPPORTED = 8,
	MIDI_ERROR_BADERRNUM = 9,
	MIDI_ERROR_INVALFLAG = 10,
	MIDI_ERROR_INVALPARAM = 11,
	MIDI_ERROR_HANDLEBUSY = 12,
	MIDI_ERROR_INVALIDALIAS = 13,
	MIDI_ERROR_BADDB = 14,
	MIDI_ERROR_KEYNOTFOUND = 15,
	MIDI_ERROR_READERROR = 16,
	MIDI_ERROR_WRITEERROR = 17,
	MIDI_ERROR_DELETEERROR = 18,
	MIDI_ERROR_VALNOTFOUND = 19,
	MIDI_ERROR_NODRIVERCB = 20,
	MIDI_ERROR_UNPREPARED = 64,
	MIDI_ERROR_STILLPLAYING = 65,
	MIDI_ERROR_NOMAP = 66,
	MIDI_ERROR_NOTREADY = 67,
	MIDI_ERROR_NODEVICE = 68,
	MIDI_ERROR_INVALIDSETUP = 69,
	MIDI_ERROR_BADOPENMODE = 70,
	MIDI_ERROR_DONT_CONTINUE = 71
}
